replicaCount: 3

image:
  repository: ghcr.io/djshat8790/quality-platform-engineering/payment-service
  tag: main
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8082

ingress:
  enabled: true
  className: nginx
  host: payment.local

resources:
  requests:
    cpu: "200m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

env:
  DB_URL: jdbc:postgresql://postgres:5432/payments
  DB_USERNAME: dheeraj
  DB_PASSWORD: password

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70

pdb:
  enabled: true
  minAvailable: 1